#ifndef HPP_DEFINES
#define HPP_DEFINES

#define SPEED_SAMPLES 10
#define PROFANITY_INVERSE_SIZE			255
#define PROFANITY_INVERSE_MULTIPLE		1024*16	//1024*16
#define PROFANITY_GLOGAL_SIZE			(PROFANITY_INVERSE_MULTIPLE * PROFANITY_INVERSE_SIZE)

#endif /* HPP_DEFINES */